name: Build binaries
on:
  push:
    branches: [main]
jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Build win.binary
        shell: bash          # ← evita el problema con PowerShell
        run: R CMD INSTALL --build .
      - uses: actions/upload-artifact@v4
        with:
          path: BIOSZEN*.zip
          name: BIOSZEN-windows
  src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Build source
        run: R CMD build .
      - uses: actions/upload-artifact@v4
        with:
          path: BIOSZEN_*.tar.gz
          name: BIOSZEN-source